### ISSUE TITLE
Exiting chat crashes server

### ISSUE THREAD

**Issue by mk6i** [mk6i/retro-aim-server#70]
The following error stack trace was reported during jawncon:

```sh
time=2024-10-11T16:20:13.180-04:00 level=INFO msg="user disconnected" svc=BOS screenName=[redacted] ip=[redacted]
panic: attempting to remove a session after its room has been deleted

goroutine 43863 [running]:
github.com/mk6i/retro-aim-server/state.(*InMemoryChatSessionManager).RemoveSession(0xc0001ae450, 0xc0001f0000)
        /home/aim/retro-aim-server/state/session_manager.go:194 +0x105
github.com/mk6i/retro-aim-server/foodgroup.AuthService.SignoutChat({{0xacda20, 0xc000220240}, {0xacd330, 0xc0001ae450}, {0xacbc70, 0xc0001ae450}, {{0xc00001e039, 0x9}, {0xc000014029, 0x4}, ...}, ...}, ...)
        /home/aim/retro-aim-server/foodgroup/auth.go:162 +0x4d
github.com/mk6i/retro-aim-server/server/oscar.ChatServer.handleNewConnection.func1()
        /home/aim/retro-aim-server/server/oscar/chat.go:81 +0x82
github.com/mk6i/retro-aim-server/server/oscar.ChatServer.handleNewConnection({{0xad02d0, 0xc00022e180}, {0xaca6a0, 0xc0002202a0}, 0xc00021e060, {0xaca720, 0xc000234000}, {{0xc00001e039, 0x9}, {0xc000014029, ...}, ...}}, ...)
        /home/aim/retro-aim-server/server/oscar/chat.go:90 +0x499
github.com/mk6i/retro-aim-server/server/oscar.ChatServer.Start.func1()
        /home/aim/retro-aim-server/server/oscar/chat.go:48 +0x7e
created by github.com/mk6i/retro-aim-server/server/oscar.ChatServer.Start in goroutine 26
        /home/aim/retro-aim-server/server/oscar/chat.go:47 +0x545
```

**Comment by mk6i** [comment]
Looks like this happens when the AIM client attempts to connect twice to the same chat room (for some reason).

It can be reproduced with this test case:

```go
func TestInMemoryChatSessionManager_RemoveSession_DoubleLogin(t *testing.T) {
	sm := NewInMemoryChatSessionManager(slog.Default())

	user1 := sm.AddSession("chat-room-1", "user-screen-name-1")
	user2 := sm.AddSession("chat-room-1", "user-screen-name-1")
	assert.NotSame(t, user1, user2)

	assert.Len(t, sm.AllSessions("chat-room-1"), 1)

	sm.RemoveSession(user1)
	sm.RemoveSession(user2)

	assert.Empty(t, sm.AllSessions("chat-room-1"))
}
```

**Comment by mk6i** [comment]
fixed @rhandorf
